package com.example.Semester_Projekt_Wettbuero_Server.Enums;

public enum RaceNames {
    GallopGalaxy,
    TrotTriumph,
    StallionSprint,
    EquineEscapade,
    RiderRally,
    HoofHeroics,
    HorsePanorama,
    SteeplechaseSpectacle,
    CanterCarnival,
    DerbyDelight,
    HoofHurricane,
    RacecourseRush,
    JockeyJubilation,
    FurlongFiesta,
    HorsePulse,
    GallopGlory,
    StallionSaga,
    ThunderThoroughbred,
    RiderRush,
    HorsepowerParade,
    ManeMarathon,
    EquineExtravaganza,
    SteeplechaseShowcase,
    HoofHustle,
    GallopGala,
    ThoroughbredThunder,
    RiderRendezvous,
    DerbyDash,
    EquestrianEpic,
}
